---
- name: Adds docker key
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution }}/gpg
    state: present

- name: Adds docker repos
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_lsb.codename }} stable"
    state: present
  tags: docker

- name: Installs docker engine
  apt:
    pkg: ["docker-ce={{ docker_version }}", "python3-pip", "python3-docker", "docker-ce-cli", "containerd.io"]
    state: present
  tags: docker
  register: __docker_installed

- name: Installs docker compose (Ubuntu > 18.04)
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    owner: root
    group: root
    mode: 0555

- name: Uninstall docker-py module
  pip:
    name: docker-py
    state: absent

- name: Adds docker options if any 1/2
  file:
    path: /etc/systemd/system/docker.service.d/
    state: directory
  when: docker_daemon_options != ""

- name: Adds docker options if any 2/2
  template:
    src: systemd_options.conf.j2
    dest: /etc/systemd/system/docker.service.d/options.conf
  when: docker_daemon_options != ""
  notify:
    - Reload systemd

- name: Flushes handlers
  meta: flush_handlers

- name: Ensure daemon is started
  service:
    name: docker
    state: started
  when: __docker_installed is changed

