---
- name: Check if docker binary exists
  ansible.builtin.stat:
    path: /usr/bin/docker
  register: __docker
  tags:
    - docker

- name: Docker tasks
  ansible.builtin.include_tasks:
    file: docker.yml
    apply:
      tags:
        - docker
  when: not __docker.stat.exists
  tags:
    - always
