---
- name: Check if docker binary exists
  stat:
    path: /usr/bin/docker
  register: __docker
  tags:
    - docker
    
- include_tasks:
    file: docker.yml
    apply:
      tags:
        - docker
  when: not __docker.stat.exists
  tags:
    - always